apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2 
kind: Deployment 
metadata: 
  name: commonservice-deployment 
spec: 
  selector: 
    matchLabels: 
      app: commonservice
  replicas: 2 # tells deployment to run 2 pods matching the template 
  template: 
    metadata: 
      labels: 
        app: commonservice
    spec: 
      containers: 
      - name: commonservice
        image: hub.binhanh.vn:5000/gpsv3_commonservice:latest
#        imagePullPolicy: Always
        ports: 
        - containerPort: 80 
--- 
# https://kubernetes.io/docs/concepts/services-networking/service/#defining-a-service  
kind: Service 
apiVersion: v1
metadata: 
  name: common-service
spec: 
  selector: 
    app: commonservice
  ports: 
  - protocol: TCP 
    port: 80 
    targetPort: 80 
    nodePort: 32202
  type: NodePort 
